# NOTE: Generated By HttpRunner v3.1.4
# FROM: .\har\wed_test.har
import allure
import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
@allure.feature("获取N天HKO.v2.xml数据")
# @pytest.mark.skip()
class TestCaseWedTest(HttpRunner):
    config = (
        Config("提取前一天的湿度")
        .variables(
            **{
                "ForecastDate": "get_day_strftime()",
                "host": "pda.weather.gov.hk",
            }
        )
        .verify(False)
        .export("dataList","dataList")
    )
    teststeps = [
        Step(
            RunRequest("/locspc/data/ocf_data/HKO.v2.xml")
            .get("${get_app_base_url()}/locspc/data/ocf_data/HKO.v2.xml")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
                    "Referer": "${get_app_base_url()}/locspc/data/ocf_data/graph/arwf/index.html?stationCode=HKO&currentHour=${ForecastDate}&device=iOS&theme=light&lang=sc",
                    "Accept-Language": "en-us",
                    "X-Requested-With": "XMLHttpRequest",
                    "Connection": "keep-alive",
                }
            )
            .extract()
            .with_jmespath("body.HourlyWeatherForecast[].[ForecastHour,ForecastRelativeHumidity]",
                           "dataList")
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal('headers."Content-Type"', "text/xml")
        )

    ]


if __name__ == "__main__":
    TestCaseWedTest().test_start()
